library_homepage:
    path:     /
    defaults: { _controller: LibraryBundle:Default:index }

library_category:
    path:   /category/{slug}
    defaults: { _controller: LibraryBundle:Category:category }

library_book:
    path:   /book/{slug}
    defaults: { _controller: LibraryBundle:Book:book }

library_author: 
    path:   /author/{slug}
    defaults: { _controller: LibraryBundle:Author:author }

library_news:
    path:    /whatsnew/
    defaults: { _controller: LibraryBundle:Default:news }

library_borrow:
    path:   /addToCart/{slug}
    defaults: { _controller: LibraryBundle:Cart:addToCart }

library_admin:
    path: /admin
    defaults: { _controller: LibraryBundle:Default:admin}

library_add_book:
    path:   /admin/add/book
    defaults: { _controller: LibraryBundle:Book:addBook }

library_edit_book:
    path:   /admin/edit/book/{slug}
    defaults: { _controller: LibraryBundle:Book:editBook }

library_remove_book:
    path:   /admin/remove/book/{slug}
    defaults: { _controller: LibraryBundle:Book:removeBook }

library_add_author:
    path:   /admin/add/author
    defaults: { _controller: LibraryBundle:Author:addAuthor }

library_edit_author:
    path:   /admin/edit/author/{slug}
    defaults: { _controller: LibraryBundle:Author:editAuthor }

library_remove_author:
    path:   /admin/remove/author/{slug}
    defaults: { _controller: LibraryBundle:Author:removeAuthor }

library_add_category:
    path:   /admin/add/category
    defaults: { _controller: LibraryBundle:Category:addCategory }

library_edit_category:
    path:   /admin/edit/category/{slug}
    defaults: { _controller: LibraryBundle:Category:editCategory }

library_remove_category:
    path:   /admin/remove/category/{slug}
    defaults: { _controller: LibraryBundle:Category:removeCategory }

library_show_cart:
    path:   /cart
    defaults: { _controller: LibraryBundle:Cart:showCart}

library_remove_cart:
    path:   /cart/remove/{slug}
    defaults: { _controller: LibraryBundle:Cart:removeFromCart }

library_checkout:
    path:   /cart/checkout
    defaults: { _controller: LibraryBundle:Loan:checkout }

library_return:
    path:   /return/{slug}
    defaults: { _controller: LibraryBundle:Loan:return }

library_loans_overview:
    path:   /admin/loans
    defaults: { _controller: LibraryBundle:Default:loansOverview}

library_user_manager:
    path:   /admin/users
    defaults: { _controller: LibraryBundle:Default:userManager}

library_user_change_status:
    path:   /admin/changestatus/{id}
    defaults: { _controller: LibraryBundle:Default:userChangeStatus}
