services:
#    library.example:
#        class: LibraryBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    library.ckeditor:
        class: LibraryBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }