<?php

namespace LibraryBundle\Entity;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike($text)
    {
        $queryBuilder = $this->createQueryBuilder('book')
            ->where("book.title LIKE :text")
            ->setParameter('text','%'.$text.'%')
        ;



        return $queryBuilder->getQuery()->getResult();
    }
}
